### ISSUE TITLE
Templates for The Events Calendar

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-theme#1347] opened 2021-05-04 17:38 UTC
**Is your feature request related to a problem? Please describe.**

> Your calendar is changing. The Events Calendar's legacy views will no longer be available as of August 03, 2021

In August, The Events Calendar will stop supporting the legacy views. We need to figure out some sort of solution to ensure Newspack sites can continue using The Events Calendar without issue after this change.

**Describe the solution you'd like**

To insulate ourselves from future Events Calendar template changes and ensure that we have a robust, well-coded Events template which doesn't mess with the `global $post` object and cause side-effects, I recommend an Events template in Newspack Theme, similar to how we have some custom WooCommerce templates.

**Describe alternatives you've considered**

It is possible to use the Page template for Events, so worst-case we can use that or add a small integration to the theme which adds a handful of extra styles to the Page template on Events. We'll need to investigate further, but there are a number of possible solutions.

**Additional context**

https://evnt.is/legacyviews

**Comment by laurelfulford** [comment] 2021-07-15 01:50
I've started digging into this and wanted to add some notes as we explore approaches:

The new views were introduced in v5.0, which was released January 27th, 2020. It looks like 3 of the 12 publishers we have running the Events Calendar plugin are already using the new views. For those who aren't there's an upgrade tab under Events > Settings. 

I will need to do some closer inspection of these new views vs the old ones, but after some cursory exploration, I think we will be able to upgrade the sites using the old views to the new ones; there does seem to be a specific 'style' and 'template' combination under the Events > Display settings (Default Events Template + Tribe Events Styles) that works best. One of the upgraded sites was using the Default Page Template, which was causing nothing to display (I've fixed this on that site). 

I suspect the three sites were just set up late enough that they got a version of the Events Calendar plugin that automatically set them with the v2 views. 

I'm not totally ruling out us needing to add or own templates -- or at least tweak some styles for the templates that are there -- but if we can avoid it, it might save us some template maintenance down the road!

**Comment by laurelfulford** [comment] 2021-07-22 01:11
Not to say this should change any of our plans, but I found [this in the Event Calendar support forums](https://wordpress.org/support/topic/massive-styling-issues-with-ver-5-5-0-and-up/#post-14616664) when digging into a more elegant way to apply the theme's custom fonts to the new views, from July 1st:

> That being said we do understand how frustrating such changes can be. As an FYI **the older legacy views will continue to work even past the August cut off date**, however we will no longer support it. Meaning when people have issues with legacy views (V1) our response will be “I’m sorry but we don’t support legacy views”. But **nothing is going to be disabled**, so you should have more time to update any custom CSS you’ve added to work with the new views (V2).

**Comment by laurelfulford** [comment] 2021-07-29 00:18
@claudiulodro so far we've landed on some changes to the theme and how the Events Calendar should be configured on publisher sites to make sure everything works and displays well with the v2 views. This is a far cry from actually building our own templates to get the events CPT behaving in a more predictable way. I wanted to check if it made sense to keep this issue open for future improvements, or close it for now and revisit potential future Events Calendar issues separately?

Personally, even with the updates, I'm not 100% confident we're not going to run into issues down the road that were missed, or that are a result of things changing in the plugin. But on the flip-side, I think any next steps will be a lower priority overall given the number of publishers on the plugin, and the potential for trying to fully roll our own templates taking up a lot of time. 

Let me know what you think!

**Comment by laurelfulford** [comment] 2021-08-09 22:24
Confirmed that this is sufficient for now; closing this issue as resolved!

**Closed by laurelfulford** 2021-08-09 22:24 UTC
Labels: [Type] Enhancement, [Status] Needs Design Review, [Status] Needs Discussion, [Pri] High, The Events Calendar
