### ISSUE TITLE
Image logo is not working on Style 1 and 3

### ISSUE THREAD

**Issue by WPArena** [Automattic/newspack-theme#568] opened 2019-11-10 23:41 UTC
Just trying to resize the image logo on style 3 and it doesn't work. Not yet checked on other styles but i think style 1 has the same issue too. Checked it.

Thanks

**Comment by laurelfulford** [comment] 2019-11-11 22:25
Thanks for this report, @WPArena! I don't think this would be Style Pack-specific -- the style packs just load different stylesheets, but don't affect the JavaScript or PHP. 

The resizing appears to work for me, but there might be something specific needed to recreate this issue. Can you please let me know:

What browser and version are you seeing this in?

Is it not resizing in the Customizer, on the front-end, or both?

If the issue is in the Customizer, do you see any JavaScript errors in the console log?

What image size and format are you starting with?

Also, if there are any other details about your setup that you think could be helpful, please share them here. Thank you!

**Comment by laurelfulford** [comment] 2020-05-21 00:18
I'm going to close this issue because I haven't been able to reproduce the issue, and we haven't gotten other reports. (Plus the theme has changed a lot since it was filed!). 

If the issue is persisting, please comment here with answers to the above comment, and I can reopen. Thanks!

**Closed by laurelfulford** 2020-05-21 00:18 UTC
Labels: [Type] Bug, can't reproduce
