### ISSUE TITLE
Please Bring a global option to enable one column or one column wide template.

### ISSUE THREAD

**Issue by SanjayKumarMonu** [Automattic/newspack-theme#675] opened 2020-01-07 10:14 UTC
Hi,

This is Sanjay, First of all I would like to congratulate you for building such an awesome theme. I became a fan of it. However, there are some features that you might take into consideration. For example, You could bring a global option in the customize section to enable one column or one column wide template to all the blog post pages.

Right now, the option to enable one column or one column wide template is present separately for each posts and pages. I meant to say that, if I would like to enable one column template on every posts pages of my site then I have to go to each post separately and then will enable the option.

Here is one more reason why this feature might be necessary.

I love Newspack theme because it gives my site the native amp support plus some great customization options. Now, because Newspack theme is providing Native AMP support, publishers like me want to run amp ads on it (mainly Google Adsense). If you know, then, Google latest responsive ad format for AMP is like this.

<amp-ad width="100vw" height="320"
     type="adsense"
     data-ad-client="ca-pub-XXXXXXXXXXXXX"
     data-ad-slot="XXXXXXXXX"
     data-auto-format="rspv"
     data-full-width="">
  <div overflow=""></div>
</amp-ad>

Now, the problem I am facing with the newspack theme enabled site by using the above adsense code is, it goes outside the container when pasting the above ad code in the article above, article below widgets (by including html widget).

Now, If the theme has a global option to enable single column or single column wide template for posts or page section. Then, placing the respective ad code doesn't initiate the above mentioned issue.

What do you think please let me know and if possible please bring a global option to enable or disable single column or single column wide template on all the posts pages.

With Regards,
Sanjay

**Comment by laurelfulford** [comment] 2020-01-07 18:33
Thanks for filing this issue, @SanjayKumarMonu!

It sounds like a duplicate of #624, though I really appreciate the extra details you've included here! I'm going to close this one, but I'll link to it from the older issue for more information.

**Closed by laurelfulford** 2020-01-07 18:33 UTC
