### ISSUE TITLE
Newspack Katharine 1.44.0 "contains outdated copies of some WooCommerce template files."

### ISSUE THREAD

**Issue by jbwhong** [Automattic/newspack-theme#1490] opened 2021-08-20 15:33 UTC
**Describe the bug**
Upon updating to Newspack Katharine 1.43.1 (and also upon updating to 1.44.0 to see if it would fix this bug) I received a message on the dashboard that says Katharine contains outdated copies of some WooCommerce template files. My WooCommerce version is 5.6.0. After clicking the button to "view affected templates" WooCommerce says: "newspack-theme/woocommerce/order/order-details-customer.php version 3.4.4 is out of date. The core version is 5.6.0"

**To Reproduce**
1. Install WooCommerce 5.6.0 and NewsPack 1.44.0 and choose the Katharine theme.
2. Go to the dashboard to see the error message

**Screenshots**
![WooCommerce error ](https://user-images.githubusercontent.com/83092901/130255275-5c5755d4-d76d-4992-b1cc-4760c14a5f86.png)

![WooCommerce error explanation](https://user-images.githubusercontent.com/83092901/130256098-b3f0f43e-7518-4c0a-b0d5-04bdfc1d653f.png)

**Expected behavior**
Since WooCommerce is a recommended plugin for NewsPack, I expected that the theme would not contain outdated versions of template files.

**Environment Details**
WP 5.8, NewsPack Theme version 1.44.0 (plugins are still 1.43.1 or whatever was latest) ; WooCommerce 5.6.0

**URL of website experiencing the issue**
https://outlookbythebay.com/

**Comment by laurelfulford** [comment] 2021-08-20 18:46
Thanks for reporting this @jbwhong! It looks a duplicate of #1486, so I'm going to close in favour of that issue; there's a fix already merged that will be available in the update next week!

**Closed by laurelfulford** 2021-08-20 18:46 UTC

**Comment by jbwhong** [comment] 2021-08-20 18:57
Thanks, @laurelfulford. I had been trying to avoid submitting a dupe but I guess I need to work on my search-fu! 😀

**Comment by laurelfulford** [comment] 2021-08-20 19:41
No worries! 😄 Some issues can be described in so many ways, it makes finding duplicates tricky!
