### ISSUE TITLE
Add Yoast Breadcrumbs code

### ISSUE THREAD

**Issue by WPArena** [Automattic/newspack-theme#633] opened 2019-12-15 04:42 UTC
Please add yoast breadcrumbs code so that we can activate it from plugin options.

Thanks

**Comment by laurelfulford** [comment] 2019-12-16 18:03
I'm going to close this as it looks like a duplicate of #626, but if there's any information you think is missing from that issue, please add it as a comment there. Thanks @WPArena!

**Closed by laurelfulford** 2019-12-16 18:03 UTC
