### ISSUE TITLE
Support of custom layout using homepage posts block for Category and Tags

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-theme#1316] opened 2021-03-29 15:05 UTC
**Is your feature request related to a problem? Please describe.**
Currently Taxonomy pages like for Category and Tags use list format to display latest articles published. 

**Describe the solution you'd like**
For a news like website it make more sense to arrange content of Category and Tags as like Homepage using Homepage posts block

**Describe alternatives you've considered**
There are few paid plugins/page builder which support this, but having this in-built will be handy

**Comment by laurelfulford** [comment] 2021-06-16 21:45
Thanks for filing this issue, @yogeshbeniwal! 

It looks like a duplicate of an existing issue, https://github.com/Automattic/newspack-theme/issues/941, so I'm going to close this version, but if you have any further information or comments you'd like to add, please add them to #941. Thank you!

**Closed by laurelfulford** 2021-06-16 21:45 UTC
Labels: Invalid/Duplicate
