### ISSUE TITLE
Primary color as header background is malfunctioning

### ISSUE THREAD

**Issue by producer-terry-turner** [Automattic/newspack-theme#507] opened 2019-10-14 01:42 UTC
**Describe the bug**

Solid Background option in "Header Settings" is malfunctioning since Alpha 10. When checked the primary color is no longer displaying the selected colour as the header background.

**To Reproduce**
1. Go to 'colors' in Appearance > Customise > 'Çolours'
2. Click on 'Custom'
3. Select a Primary Colour
4. Publish Change
5. Go to 'colors' in Appearance > Customise > 'Header Settings'
6. Check 'Solid Background'
7. Publish Change
8. Go to 'colors' in Appearance > Customise > 'Style Packs'

You will note that the custom header background is no longer applied.

**Note**
Reverting to Alpha 9 THEME fixed this issue.

**Expected behavior**
The header background should have changed according to the color selected, as per Alpha 9.

**Comment by laurelfulford** [comment] 2019-10-14 18:27
Thanks for this report, @producer-terry-turner! 

We did make some changes in Alpha 10 to Style Pack 5, so that it would always use a black header when the 'Solid Background' option was selected, rather than the primary colour (this is similar to how style packs 3 and 4 also work). Is this what you're seeing?

If not, can you please let us know which one you're seeing this with? Can you also confirm if you're seeing this on the front-end, or only in the Customizer?

If you're able to attach a screenshot, that would also be a big help.

Thank you for your help! 🙌

**Comment by producer-terry-turner** [comment] 2019-10-15 03:08
When the solid background option is selected, the primary color is not
being seen across any of the five styles within the customizer, or on the
front-end.

It is instead displaying the black, or Newspack blue color scheme.

When the solid background option is not selected, it is displaying white or
black across the styles.

Hope that assists.

**Comment by laurelfulford** [comment] 2019-10-15 20:36
Thanks @producer-terry-turner! 

I'm a bit stumped -- this seems to be working as expected for me. But I'm wondering if it has to do with some of the CSS-reworking we did around the header recently.

It's a stretch, but could you please try clearing the browser cache, and testing the front-end again? We changed the elements we were applying the background colour to in the header's CSS, I wonder if it's partly loading old CSS and partly loading new customizations, if it's not quite coming together as expected. 

Please let me know how this goes, and I'll report back if I think of anything else!

**Comment by laurelfulford** [comment] 2020-05-21 00:16
I'm going to close this issue as I wasn't able to reproduce, and haven't had further reports.

**Closed by laurelfulford** 2020-05-21 00:16 UTC
Labels: [Type] Bug, can't reproduce
